api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_swagger_ui: '%env(bool:ENABLE_SWAGGER)%'
    enable_docs: '%env(bool:ENABLE_SWAGGER)%'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
